version: "3"
services:
  postgres:
    image: postgres:11.5-alpine
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./ps-first-spring-boot-app/database/postgresql/1_create_tables.sql:/docker-entrypoint-initdb.d/1_create_tables.sql
      - ./ps-first-spring-boot-app/database/postgresql/2_insert_data.sql:/docker-entrypoint-initdb.d/2_insert_data.sql
      - ./ps-first-spring-boot-app/database/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Welcome
      POSTGRES_DB: conference_app

